# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build & Package CO2 Calculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🔧 Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: 📦 Build with Maven
        run: mvn clean package

      - name: 🎯 Make JAR Executable
        run: chmod +x target/co2-calculator-0.0.1-SNAPSHOT.jar

      - name: 🚀 Run Tests
        run: mvn test

      - name: 🔥 Install GraalVM
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc musl-dev
          curl -L https://github.com/graalvm/graalvm-ce-builds/releases/latest/download/graalvm-ce-java21-linux-amd64.tar.gz -o graalvm.tar.gz
          tar -xzf graalvm.tar.gz
          sudo mv graalvm-ce-java21-* /opt/graalvm
          echo "export PATH=/opt/graalvm/bin:$PATH" >> $GITHUB_ENV
          echo "export JAVA_HOME=/opt/graalvm" >> $GITHUB_ENV
          /opt/graalvm/bin/gu install native-image

      - name: 🏗️ Build Native Executable
        run: |
          /opt/graalvm/bin/native-image -jar target/co2-calculator-0.0.1-SNAPSHOT.jar co2-calculator
          chmod +x co2-calculator

      - name: 📤 Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: co2-calculator
          path: co2-calculator


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
